'use strict';

const HB_QUEUE_STATUS_CONSTANTS = {
	STATUS_QUEUE_COMPLETE: "QueueCore work done",
	STATUS_QUEUE_SCANNED_READY: "ScanCore scan done"
}

const RIP_PROGRESS_CONSTANTS = {
	ENCODE_STARTED: "QueueCore started encoding "
};

const STATUS = {
	SCAN_COMPLETE: 'SCAN_COMPLETE',
	QUEUE_COMPLETE: 'QUEUE_COMPLETE',
	WORKING: 'WORKING',
	PEER_UNAVAILABLE: 'PEER_UNAVAILABLE'
}

module.exports = {
	HB_QUEUE_STATUS_CONSTANTS,
	STATUS,
	RIP_PROGRESS_CONSTANTS
};
